[GENERAL]
PORT = 3001 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"

[API_KEYS]
OPENAI = "${OPENAI_API_KEY}" # OpenAI API key
GROQ = "${GROQ_API_KEY}" # Groq API key
ANTHROPIC = "${ANTHROPIC_API_KEY}" # Anthropic API key

[API_ENDPOINTS]
SEARXNG = "${SEARXNG_API_URL}" # SearxNG API URL
OLLAMA = "${OLLAMA_API_URL}" # Ollama API URL
